const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
const GET_TABLE_DATA_LOADING = "GET_TABLE_DATA_LOADING";
const GET_TABLE_DATA_FAILURE = "GET_TABLE_DATA_FAILURE";

const ADD_POST_LOADING = "ADD_POST_LOADING";
const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
const ADD_POST_FAILURE = "ADD_POST_FAILURE";

export {
  GET_TABLE_DATA_FAILURE,
  GET_TABLE_DATA_LOADING,
  GET_TABLE_DATA_SUCCESS,
  ADD_POST_FAILURE,
  ADD_POST_LOADING,
  ADD_POST_SUCCESS,
};
