const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
const GET_TABLE_DATA_LOADING = "GET_TABLE_DATA_LOADING";
const GET_TABLE_DATA_FAILURE = "GET_TABLE_DATA_FAILURE";

export {
  GET_TABLE_DATA_FAILURE,
  GET_TABLE_DATA_LOADING,
  GET_TABLE_DATA_SUCCESS,
};
